COMMON: &COMMON
  signup_points: 2000
  initial_lot_per_lane: 1000
  deposit_points: 100
  price_scale_number: 1
  transaction_fee: 0.01
  investment_limit: 100
  category: [Health & Life, Policy, Products, Sports, Entertainment, Tech]
  chat_domain: "http://chat.delicracy.com"
  pm_domain: "http://beta.delicracy.com"

development:
  <<: *COMMON

test:
  <<: *COMMON

production:
  <<: *COMMON
