production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  facebook_id: <%= ENV['FACEBOOK_ID'] %>
  facebook_key: <%= ENV['FACEBOOK_KEY'] %>
  kakao_key: <%= ENV['KAKAO_KEY'] %>
  kakao_secret: <%= ENV['KAKAO_SECRET'] %>
